version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db:/var/lib/postgresql/data
    network_mode: "host"

  flask:
    build: .
    container_name: flask
    volumes:
      - .:/code
    network_mode: "host"
volumes:
  db:
    driver: local

